server:
  port: 8090
  url: http://localhost:8090
  prod:
    url: https://api.foodapp.com


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/foodapp_dev
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none        # VERY IMPORTANT
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  flyway:
    enabled: true
    baseline-on-migrate: true
    validate-on-migrate: true
    locations: classpath:db/migration


  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true



  redis:
    host: localhost
    port: 6379

  cache:
    type: redis
    redis:
      time-to-live: 600000   # 600000 ms = 10 minutes





aws:
  s3:
    region: ap-south-1
    bucket: food-bytebyteboot-dev

  accessKeyId: ${AWS_ACCESS_KEY_ID}
  secretKey: ${AWS_SECRET_KEY}




## LOCAL REACT FRONTEND
frontend:
  base:
    url: http://localhost:3000

base:
  payment:
    link: http://localhost:3000/pay?orderid=



stripe:
  api:
    public:
      key: ${STRIPE_PUBLIC_KEY}
    secret:
      key: ${STRIPE_SECRET_KEY}


# Rate Limiter Configuration
rate:
  limit:
    general-capacity: 100
    general-refill-rate: 100

    auth-capacity: 3
    auth-refill-rate: 3

    write-capacity: 20
    write-refill-rate: 20

    admin-capacity: 50
    admin-refill-rate: 50

    upload-capacity: 10
    upload-refill-rate: 10


springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    operations-sorter: method
    tags-sorter: alpha
    try-it-out-enabled: true
    filter: true
    syntax-highlight:
      activated: true
  show-actuator: false
  packages-to-scan: com.bytebyteboot.foodapp
  paths-to-match: /api/**

# Application Info
app:
  name: Food Delivery API
  version: 1.1.0
  description: Complete Food Delivery Management System

# Disable Swagger in Production (optional)
# springdoc:
#   swagger-ui:
#     enabled: false